import pgPromise from "../../pgPromise";

const db = pgPromise

db.none(`create table if not exists projects (
  id int primary key generated by default as identity,
  title varchar(150) not null,
  description text not null,
  snapshot varchar(200) not null,
  github_link varchar(150) not null,
  last_update date not null
);`);

export default db
