networks:
  ikatoo-db-net:
    external: false

services:

  postgres:
    container_name: ${POSTGRES_HOSTNAME}
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    ports:
      - 5432:5432
    networks:
      - ikatoo-db-net
  
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      ADMINER_DEFAULT_SERVER: ${POSTGRES_HOSTNAME}
    networks:
      - ikatoo-db-net