services:

  postgres:
    container_name: ${POSTGRES_HOSTNAME}
    image: postgres:14-alpine
    volumes:
      - ./db/scripts:/db/scripts
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    ports:
      - 5432:5432
  
  adminer:
    image: adminer
    restart: always
    links:
      - postgres
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      ADMINER_DEFAULT_SERVER: ${POSTGRES_HOSTNAME}
