import { env } from "@/env";
import pgPromise from "pg-promise";

const pgp = pgPromise({});

const db = pgp({
  user: env.POSTGRES_USER,
  password: env.POSTGRES_PASSWORD,
  host: env.NODE_ENV === "test" ? "localhost" : env.POSTGRES_HOSTNAME,
  port: env.POSTGRES_PORT,
  database: env.POSTGRES_DBNAME,
  idleTimeoutMillis: 100,
});

db.none(`create table if not exists skills (
  id int primary key generated by default as identity,
  title varchar(150) not null,
  description text not null
);`);

db.none(`create table if not exists jobs (
  id int primary key generated by default as identity,
  title varchar(150) not null,
  description text not null,
  link varchar(150) not null,
  start date not null,
  "end" date not null default current_date
);`);

db.none(`create table if not exists about_page (
  id int primary key generated by default as identity,
  title varchar(150) not null,
  description text not null,
  illustration_url varchar(200),
  illustration_alt varchar(200)
);`);

export default db;
