import { env } from '@/utils/env'
import pgPromise from 'pg-promise'

const pgp = pgPromise({})

if (!global.PG_PROMISE_DB) {
  global.PG_PROMISE_DB = pgp({
    user: env.POSTGRES_USER,
    password: env.POSTGRES_PASSWORD,
    host: (env.NODE_ENV === "test" || env.NODE_ENV === "dev") ? "localhost" : env.POSTGRES_HOSTNAME,
    port: env.POSTGRES_PORT,
    database: env.POSTGRES_DBNAME,
    idleTimeoutMillis: 100
  })
  const db = global.PG_PROMISE_DB;
  function initDb() {
    console.log('INIT DATABASE...')
    db.none(`create table if not exists about_page (
      title varchar(150) unique not null,
      description text not null,
      skills json,
      illustration_url varchar(200),
      illustration_alt varchar(200)
      );`);

    db.none(`create table if not exists contacts_page (
      title varchar(150) unique not null,
      description text not null,
      localization point
    );`);

    db.none(`create table if not exists projects (
      id int primary key generated by default as identity,
      title varchar(150) unique not null,
      description text not null,
      snapshot varchar(200) not null,
      github_link varchar(150) not null,
      last_update date not null
    );`);

    db.none(`create table if not exists skills_page (
      title varchar(150) unique not null,
      description text not null,
      skills json,
      last_jobs json
    );`);
  }

  initDb()
}

const db = global.PG_PROMISE_DB;

export default db