import { env } from '@/utils/env'
import pgPromise from 'pg-promise'

const pgp = pgPromise({})

global.PG_PROMISE_DB = global.PG_PROMISE_DB ?? pgp({
  user: env.POSTGRES_USER,
  password: env.POSTGRES_PASSWORD,
  host: (env.NODE_ENV === "test" || env.NODE_ENV === "dev") ? "localhost" : env.POSTGRES_HOSTNAME,
  port: env.POSTGRES_PORT,
  database: env.POSTGRES_DBNAME,
  idleTimeoutMillis: 100
})

const db = global.PG_PROMISE_DB;

const initDb = async () => {
  await db.none(`create table if not exists about_page (
    id int primary key generated by default as identity,
    title varchar(150) not null,
    description text not null,
    illustration_url varchar(200),
    illustration_alt varchar(200)
    );`);

  await db.none(`create table if not exists contacts_page (
    id int primary key generated by default as identity,
    title varchar(150) not null,
    description text not null
  );`);

  await db.none(`create table if not exists contacts (
    id int primary key generated by default as identity,
    email varchar(150) unique not null,
    localization point,
    contact_page_id int,
    FOREIGN KEY (contact_page_id) REFERENCES contacts_page (id)
  );`);

  await db.none(`create table if not exists jobs (
    id int primary key generated by default as identity,
    title varchar(150) not null,
    description text not null,
    link varchar(150) not null,
    start date not null,
    "end" date not null default current_date
  );`);

  await db.none(`create table if not exists projects (
    id int primary key generated by default as identity,
    title varchar(150) not null,
    description text not null,
    snapshot varchar(200) not null,
    github_link varchar(150) not null,
    last_update date not null
  );`);

  await db.none(`create table if not exists projects_page (
    id int primary key generated by default as identity,
    title varchar(150) not null,
    description text not null
  );`);

  await db.none(`create table if not exists skills (
    id int primary key generated by default as identity,
    title varchar(150) not null,
    description text,
    about_page_id int,
    FOREIGN KEY (about_page_id) REFERENCES about_page (id)
    );`);

  await db.none(`create table if not exists skills_jobs (
    job_id int not null,
    skill_id int not null,
    FOREIGN KEY (job_id) REFERENCES jobs (id),
    FOREIGN KEY (skill_id) REFERENCES skills (id)
  );`);

  await db.none(`create table if not exists skills_page (
    id int primary key generated by default as identity,
    title varchar(150) not null,
    description text not null
  );`);
}

initDb()

export default db