import pgPromise from "../../pgPromise";

const db = pgPromise


db.none(`create table if not exists about_page (
  id int primary key generated by default as identity,
  title varchar(150) not null,
  description text not null,
  illustration_url varchar(200),
  illustration_alt varchar(200)
  );`);

export default db