import pgPromise from "../../pgPromise";

const db = pgPromise

db.none(`create table if not exists projects_page (
  id int primary key generated by default as identity,
  title varchar(150) not null,
  description text not null
);`);

export default db
