import pgPromise from "../../pgPromise";

const db = pgPromise

db.none(`create table if not exists contacts (
  id int primary key generated by default as identity,
  email varchar(150) unique not null,
  localization point
);`);

export default db