import pgPromise from "../../pgPromise";

const db = pgPromise

db.none(`create table if not exists skills (
  id int primary key generated by default as identity,
  title varchar(150) not null,
  description text,
  about_page_id int
);`);

export default db