name: Tests Workflow on Pull Request
on: pull_request
    
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      matrix:
        node: [18]
    env:
      NODE_ENV: ci
      PORT: 8000
      HOST: localhost
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DBNAME: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOSTNAME: postgres
      CLOUDNARY_CLOUDNAME: test
      CLOUDNARY_FOLDER: test
      CLOUDNARY_APIKEY: test
      CLOUDNARY_APISECRET: test
      CLOUDINARY_URL: cloudinary://123:asdf234@cloudname
      SMTP_SERVER_ADDRESS: smtp.ethereal.email
      SMTP_SERVER_PORT: 587
      SMTP_USERNAME: nelda40@ethereal.email
      SMTP_PASSWORD: MBeHrSTvuCq2MVzQWp
      SMTP_SECURE: false

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    container:
      image: postgres:14
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Create Tables
        env:
          PGPASSWORD: postgres
        run: psql -v ON_ERROR_STOP=1 --host postgres --username postgres --dbname postgres -a -f db/scripts/init.sql
    
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
    
      - name: Install Dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Test
        env:
          NODE_ENV: ci
        run: npx vitest run

      - name: Send email when fail tests
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: mckatoo@outlook.com
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Failed tests
          to: mckatoo@gmail.com
          from: iKatoo Repository
          html_body: Tests of the repository <a href="https://github.com/${{github.repository}}/tree/${{github.ref_name}}">${{github.repository}}</a> if failed. Please, verify and fix de code.